<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-14 08:46

import django.utils.timezone
=======
# Generated by Django 5.2.6 on 2025-09-26 15:28

>>>>>>> 25d3f77 (Deployment files setup and project initialization)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
<<<<<<< HEAD
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
=======
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
>>>>>>> 25d3f77 (Deployment files setup and project initialization)
            ],
        ),
    ]
